#!/bin/sh
#
# nginxmgr - this script starts and stops the nginxmgr daemon
#
# chkconfig:   - 85 15
# description:  Nginxmgr is a health-check/config manager daemon \
#               for nginx.

# config:      /etc/nginxmgr/nginxmgr.cfg

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0


nginxmgr="/usr/bin/nginxmgr"
prog=$(basename $nginxmgr)

NGINXMGR_CONF_FILE="/etc/nginxmgr/nginxmgr.cfg"

[ -f /etc/sysconfig/nginxmgr ] && . /etc/sysconfig/nginxmgr

lockfile=/var/lock/subsys/nginxmgr


start() {
    [ -x $nginxmgr ] || exit 5
    [ -f $NGINXMGR_CONF_FILE ] || exit 6
    echo -n $"Starting $prog: " 
    daemon $nginxmgr -c $NGINXMGR_CONF_FILE
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: " 
    killproc $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status|status_q)
        rh_$1
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
